name: Build Binaries
on:
  workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build Binary (*nix)
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          /bin/bash scripts/build.sh
      - name: Build Binary (win32)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          scripts/build.bat
      - uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: |
            dist/*
  